version: "3.9"

services:
  nginx:
    image: bitnami/nginx:latest
    ports:
      - 81:80
    volumes:
      - ./conf/nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
      - ./conf/nginx/app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf
      - ./conf/nginx/hhvm.conf:/opt/bitnami/nginx/conf/server_blocks/hhvm.conf
      - ../../app:/app
      - /tmp/sock:/tmp/sock
    networks:
      - net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app
  app:
    build:
      dockerfile: docker/main/builds/app.Dockerfile
      context: ../../
    volumes:
      - ../../app:/app
      - ./.env:/app/.env
      - ./conf/app/php.ini:/opt/bitnami/php/etc/conf.d/common.ini
      - ./conf/app/common.conf:/opt/bitnami/php/etc/common.conf
      - /tmp/sock:/tmp/sock
    tty:
      true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - RABBITMQ_PORT=$RABBITMQ_NETWORK_PORT
      - POSTGRESQL_PORT=$POSTGRESQL_NETWORK_PORT
      - REDIS_PORT=$REDIS_NETWORK_PORT
    networks:
      - net
    depends_on:
      - postgresql
    command:
      /start.sh
  postgresql:
    image: bitnami/postgresql:12
    ports:
      - $POSTGRESQL_PORT:$POSTGRESQL_NETWORK_PORT
    tty: true
    volumes:
      - ./db/postgresql:/bitnami/postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_POSTGRES_PASSWORD=$POSTGRESQL_POSTGRES_PASS
      - POSTGRESQL_USERNAME=$POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD=$POSTGRESQL_PASS
      - POSTGRESQL_DATABASE=$POSTGRESQL_DB_NAME
    networks:
      - net
networks:
  net:
    driver: bridge