version: "3.9"

services:
  nginx:
    image: bitnami/nginx:latest
    ports:
      - 81:80
    volumes:
      - ./conf/nginx/nginx.conf:/opt/bitnami/nginx/conf/nginx.conf
      - ./conf/nginx/app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf
      - ../../app:/app
      - /tmp/sock:/tmp/sock
    networks:
      - net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app
  app:
    build:
      dockerfile: docker/local/builds/app.Dockerfile
      context: ../../
    volumes:
      - ../../app:/app
      - ./.env:/app/.env
      - ./conf/app/php.ini:/opt/bitnami/php/etc/conf.d/common.ini
      - ./conf/app/common.conf:/opt/bitnami/php/etc/common.conf
      - /tmp/sock:/tmp/sock
    tty:
      true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - RABBITMQ_PORT=$RABBITMQ_NETWORK_PORT
      - POSTGRESQL_PORT=$POSTGRESQL_NETWORK_PORT
      - REDIS_PORT=$REDIS_NETWORK_PORT
    networks:
      - net
    depends_on:
      - postgresql
      - rabbitmq
      - redis
    command:
      /start.sh
  hhvm:
    build:
      dockerfile: docker/local/builds/hhvm.Dockerfile
      context: ../../
    ports:
      - 9005:9000
    volumes:
      - ../../app:/var/www
      - ./.env:/app/.env
      - /tmp:/tmp
      - ./conf/hhvm/server.ini:/etc/hhvm/server.ini
    tty:
      true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - POSTGRESQL_PORT=$POSTGRESQL_NETWORK_PORT
    networks:
      - net
    entrypoint: /usr/bin/hhvm -m server -c /etc/hhvm/server.ini
  postgresql:
    image: bitnami/postgresql:12
    ports:
      - $POSTGRESQL_PORT:$POSTGRESQL_NETWORK_PORT
    tty: true
    volumes:
      - ./db/postgresql:/bitnami/postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_POSTGRES_PASSWORD=$POSTGRESQL_POSTGRES_PASS
      - POSTGRESQL_USERNAME=$POSTGRESQL_USERNAME
      - POSTGRESQL_PASSWORD=$POSTGRESQL_PASS
      - POSTGRESQL_DATABASE=$POSTGRESQL_DB_NAME
    networks:
      - net
  rabbitmq:
    build:
      dockerfile: rabbitmq.Dockerfile
      context: ./builds
    ports:
      - $RABBITMQ_PORT:$RABBITMQ_NETWORK_PORT
      - 15672:15672
      - 15692:15692
    volumes:
      - ./conf/rabbitmq/custom.conf:/bitnami/rabbitmq/conf/custom.conf:ro
    environment:
      - RABBITMQ_USERNAME=$RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD=$RABBITMQ_PASS
      - RABBITMQ_NODE_NAME=$RABBITMQ_NODE_NAME
      - RABBITMQ_PLUGINS=$RABBITMQ_PLUGINS
#    hostname: $RABBITMQ_HOSTNAME
    networks:
      - net
  redis:
    build:
      dockerfile: docker/local/builds/redis.Dockerfile
      context: ../../
    ports:
      - $REDIS_PORT:$REDIS_NETWORK_PORT
    volumes:
      - ./db/redis:/bitnami/redis/data
      - /tmp/sock:/tmp/sock
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_USERNAME=$REDIS_USERNAME
      - REDIS_PASSWORD=$REDIS_PASS
    networks:
      - net
  redmin:
    image: faktiva/php-redis-admin
    ports:
      - "8520:80"
    tty:
      true
    volumes:
      - ./conf/redmin/config.php:/var/www/html/php-redis-admin/app/config/config.php
    depends_on:
      - redis
    networks:
      - net
networks:
  net:
    driver: bridge