version: "3.9"

services:
  rabbitmq:
    build:
      dockerfile: docker/rabbitmq/builds/rabbitmq.Dockerfile
      context: ../../
    ports:
      - $RABBITMQ_PORT:$RABBITMQ_NETWORK_PORT
      - 15672:15672
      - 15692:15692
    volumes:
      - ../rabbitmq/conf/rabbitmq/custom.conf:/bitnami/rabbitmq/conf/custom.conf:ro
    environment:
      - RABBITMQ_USERNAME=$RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD=$RABBITMQ_PASS
      - RABBITMQ_NODE_NAME=$RABBITMQ_NODE_NAME
      - RABBITMQ_PLUGINS=$RABBITMQ_PLUGINS
#    hostname: $RABBITMQ_HOSTNAME
    networks:
      - net
networks:
  net:
    driver: bridge